// AUTHENTICATION
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const AUTH_USER = 'AUTH_USER'

export const VERIFY_EMAIL_RESOLVED = 'VERIFY_EMAIL_RESOLVED'
export const VERIFY_EMAIL_PENDING = 'VERIFY_EMAIL_PENDING'
export const VERIFY_EMAIL_REJECTED = 'VERIFY_EMAIL_REJECTED'

export const VERIFY_TOKEN_RESOLVED = 'VERIFY_TOKEN_RESOLVED'
export const VERIFY_TOKEN_PENDING = 'VERIFY_TOKEN_PENDING'
export const VERIFY_TOKEN_REJECTED = 'VERIFY_TOKEN_REJECTED'

// APPLICATION
export const FETCH_TOURS_RESOLVED = 'FETCH_TOURS_RESOLVED'
export const FETCH_TOURS_PENDING = 'FETCH_TOURS_PENDING'
export const FETCH_TOURS_REJECTED = 'FETCH_TOURS_REJECTED'

export const FETCH_SHOWS_RESOLVED = 'FETCH_SHOWS_RESOLVED'
export const FETCH_SHOWS_PENDING = 'FETCH_SHOWS_PENDING'
export const FETCH_SHOWS_REJECTED = 'FETCH_SHOWS_REJECTED'

export const FETCH_ORDERS_RESOLVED = 'FETCH_ORDERS_RESOLVED'
export const FETCH_ORDERS_PENDING = 'FETCH_ORDERS_PENDING'
export const FETCH_ORDERS_REJECTED = 'FETCH_ORDERS_REJECTED'

export const SEARCH_TOURS = 'SEARCH_TOURS'
export const SEARCH_SHOWS = 'SEARCH_SHOWS'
export const SEARCH_ORDERS = 'SEARCH_ORDERS'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'

// EMAIL
export const FETCH_EMAIL_RESOLVED = 'FETCH_EMAIL_RESOLVED'
export const FETCH_EMAIL_PENDING = 'FETCH_EMAIL_PENDING'
export const FETCH_EMAIL_REJECTED = 'FETCH_EMAIL_REJECTED'

export const SAVE_EMAIL_RESOLVED = 'SAVE_EMAIL_RESOLVED'
export const SAVE_EMAIL_PENDING = 'SAVE_EMAIL_PENDING'
export const SAVE_EMAIL_REJECTED = 'SAVE_EMAIL_REJECTED'

export const SEND_EMAIL_RESOLVED = 'SEND_EMAIL_RESOLVED'
export const SEND_EMAIL_PENDING = 'SEND_EMAIL_PENDING'
export const SEND_EMAIL_REJECTED = 'SEND_EMAIL_REJECTED'

// USER
export const UPDATE_USER_RESOLVED = 'UPDATE_USER_RESOLVED'
export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING'
export const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED'

export const FETCH_USERS_RESOLVED = 'FETCH_USERS_RESOLVED'
export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING'
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED'

export const DELETE_USER_RESOLVED = 'DELETE_USER_RESOLVED'
export const DELETE_USER_PENDING = 'DELETE_USER_PENDING'
export const DELETE_USER_REJECTED = 'DELETE_USER_REJECTED'

export const INVITE_USER_RESOLVED = 'INVITE_USER_RESOLVED'
export const INVITE_USER_PENDING = 'INVITE_USER_PENDING'
export const INVITE_USER_REJECTED = 'INVITE_USER_REJECTED'

// MODAL ACTIONS
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

// MODAL TYPES
export const MAKE_ADMIN = 'MAKE_ADMIN'
export const REMOVE_ADMIN = 'REMOVE_ADMIN'
export const DELETE_USER = 'DELETE_USER'
export const INVITE_USER = 'INVITE_USER'
